from . import algebra
from . import basic
from . import chess
from . import codeforces
from . import game_theory
from . import graphs
from . import ICPC
from . import IMO
from . import puzzles
from . import trivial